language: go

matrix:
  include:
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: master
  allow_failures:
    - go: master

before_install:
  - mkdir -p bin
  - curl -Lso bin/shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.3/shellcheck
  - chmod +x bin/shellcheck
script:
  - GOPKGS_NOVENDOR=$(go list ./... | grep -v /vendor/)
  - GOFILES_NOVENDOR=$(find . -type f -name '*.go' -not -path "*/vendor/*")
  - PATH=$PATH:$PWD/bin go test -v $GOPKGS_NOVENDOR
  - go build
  - diff -u <(echo -n) <(gofmt -d -s $GOFILES_NOVENDOR)
  - if [ -z $NOVET ]; then
      diff -u <(echo -n) <(go vet $GOPKGS_NOVENDOR 2>&1 | grep -vE 'ExampleCommand|bash_completions.*Fprint');
    fi
