language: go
arch: 
 - amd64
 - ppc64le
stages:
  - diff
  - test
  - build

go:
  - 1.12.x
  - 1.13.x
  - tip

before_install:
  - go get -u github.com/kyoh86/richgo
  - go get -u github.com/mitchellh/gox

matrix:
  allow_failures:
    - go: tip
  include:
    - stage: diff
      go: 1.13.x
      script: make fmt
    - stage: build
      go: 1.13.x
      script: make cobra_generator
      
# power support 
    - stage: diff
      go: 1.13.x
      arch : ppc64le
      script: make fmt
    - stage: build
      go: 1.13.x
      arch: ppc64le
      script: make cobra_generator
# Disable version Go 1.12.x
jobs:
  exclude:
    - arch: ppc64le
     go: 1.12.x
script: 
 - make test
