language: go

stages:
  - diff
  - test

matrix:
  include:
    - go: 1.11.x
    - go: 1.12.x
    - go: tip
    - stage: diff
      go: 1.12.x
      script: diff -u <(echo -n) <(gofmt -d -s .)
  allow_failures:
    - go: tip

before_install:
  - mkdir -p bin
  - curl -Lso bin/shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.6/shellcheck
  - chmod +x bin/shellcheck
script:
  - PATH=$PATH:$PWD/bin go test -v ./...
  - go build
  - if [ -z $NOVET ]; then
      diff -u <(echo -n) <(go vet . 2>&1 | grep -vE 'ExampleCommand|bash_completions.*Fprint');
    fi
